namespace Procurable.Migrations
{
    using Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Procurable.Models.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "Procurable.Models.ApplicationDbContext";
        }

        protected override void Seed(Procurable.Models.ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            var vendors = new List<Vendor>();
            
            vendors.Add( new Vendor() { ID = 1, Name = "Acer", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 2, Name = "Gateway", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 3, Name = "Packard Bell", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 4, Name = "Advent", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 5, Name = "A-EON Technology", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 6, Name = "ACube Systems Srl", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 7, Name = "Aigo", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 8, Name = "AMD", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 9, Name = "Aleutia", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 10, Name = "AMAX Information Technologies", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 11, Name = "Ankermann", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 12, Name = "AORUS", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 13, Name = "AOpen", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 14, Name = "Apple", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 15, Name = "ASRock", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 16, Name = "Asus", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 17, Name = "AVADirect", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 18, Name = "AXIOO International", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 19, Name = "BenQ", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 20, Name = "Biostar", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 21, Name = "BOXX Technologies, Inc.", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 22, Name = "Chassis Plans", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 23, Name = "Chillblast", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 24, Name = "Chip PC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 25, Name = "Clevo", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 26, Name = "Sager Notebook Computers", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 27, Name = "Cray", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 28, Name = "Crystal Group", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 29, Name = "Cybernet Computer Inc.", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 30, Name = "Compal", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 31, Name = "Cooler Master", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 32, Name = "CyberPower PC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 33, Name = "Dell", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 34, Name = "Wyse Technology", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 35, Name = "DFI", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 36, Name = "Digital Storm", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 37, Name = "Doel (computer)", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 38, Name = "Evans & Sutherland", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 39, Name = "Everex", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 40, Name = "EVGA", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 41, Name = "Falcon Northwest", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 42, Name = "FIC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 43, Name = "Fujitsu", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 44, Name = "Fusion Red", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 45, Name = "Foxconn", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 46, Name = "Founder Technology", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 47, Name = "Getac", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 48, Name = "Gigabyte", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 49, Name = "Gradiente", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 50, Name = "Groupe Bull", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 51, Name = "Hasee", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 52, Name = "Hewlett-Packard (HP)", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 53, Name = "Compaq", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 54, Name = "Hitachi", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 55, Name = "HTC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 56, Name = "Hyundai", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 57, Name = "IBM", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 58, Name = "IBuyPower", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 59, Name = "Intel", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 60, Name = "Inventec", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 61, Name = "In-Win", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 62, Name = "Itautec", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 63, Name = "IGEL", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 64, Name = "Jetta International", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 65, Name = "Kohjinsha", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 66, Name = "Kontron AG", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 67, Name = "LanFirePC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 68, Name = "Lanix", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 69, Name = "Lanner Electronics", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 70, Name = "LanSlide Gaming PCs", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 71, Name = "Lenovo", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 72, Name = "Medion", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 73, Name = "LG", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 74, Name = "LiteOn", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 75, Name = "Maingear", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 76, Name = "MDG Computers", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 77, Name = "Meebox", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 78, Name = "Mesh Computers", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 79, Name = "Micron", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 80, Name = "Microsoft", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 81, Name = "Micro-Star International (MSI)", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 82, Name = "Micro Center", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 83, Name = "MiTAC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 84, Name = "Motion Computing", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 85, Name = "Motorola", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 86, Name = "NComputing", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 87, Name = "NCR", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 88, Name = "NEC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 89, Name = "NUDT", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 90, Name = "NZXT", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 91, Name = "Olidata", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 92, Name = "Olivetti", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 93, Name = "Oracle", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 94, Name = "Origin PC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 95, Name = "Panasonic", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 96, Name = "Positivo Informática", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 97, Name = "Psychsoftpc", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 98, Name = "Puget Systems", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 99, Name = "Quanta Computer", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 100, Name = "RCA", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 101, Name = "Razer", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 102, Name = "RoseWill", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 103, Name = "Samsung", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 104, Name = "Sapphire Technology", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 105, Name = "Sharp Corporation", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 106, Name = "Shuttle", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 107, Name = "SGI", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 108, Name = "Síragon", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 109, Name = "Sony", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 110, Name = "StealthMachines", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 111, Name = "Supermicro", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 112, Name = "Systemax", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 113, Name = "System76", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 114, Name = "T-Platforms", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 115, Name = "TabletKiosk", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 116, Name = "Tadpole Computer", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 117, Name = "Tatung", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 118, Name = "Toshiba", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 119, Name = "Tyan", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 120, Name = "Unisys", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 121, Name = "V3 Gaming PC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 122, Name = "Velocity Micro", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 123, Name = "Overdrive PC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 124, Name = "Vestel", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 125, Name = "Venom", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 126, Name = "VIA Technologies", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 127, Name = "ViewSonic", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 128, Name = "Viglen", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 129, Name = "Virus Computers Inc.", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 130, Name = "Vizio", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 131, Name = "VT Miltope", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 132, Name = "WidowPC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 133, Name = "Wistron", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 134, Name = "Wortmann", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 135, Name = "Xidax", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 136, Name = "Zelybron", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 137, Name = "Zombie PC", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 138, Name = "Zoostorm", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.Add( new Vendor() { ID = 139, Name = "Zotac", Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet iaculis orci. Aliquam suscipit laoreet massa id fringilla. Phasellus quis dignissim dolor, a tempus tellus. Curabitur sed pulvinar lacus. Vivamus vel ornare massa, in interdum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus justo, dictum sit amet ultrices et, mollis eget massa. Cras porta lacus mauris, id pellentesque arcu convallis ac", Website = "http://example.com" });
            vendors.ForEach(s => context.Vendors.AddOrUpdate(p => p.ID, s));

            context.InventoryItems.AddOrUpdate(x => x.ID, new InventoryItem() { ID =5, VendorID=1, Comments = "This is a comment", Name = "Computer", Price = new decimal(143.33), PartNumber = "12030201", Status = InventoryStatus.Unallocated });
        }
    }
}
